### PR TITLE
BuckleScript support, and bump to 0.5.2

### PR DESCRIPTION
**Pull request by ELLIOTTCABLE**
As requested!

Couple notes: 1. Formatting in the README felt a little strange to me, but I opted to maintain the existing style rather than try to unilaterally ‘fix’ it. Hopefully it works out to your standards! 2. I tend towards very granular commits, again, hope you don't mind the volume of individual changes (ignore anything with the `-` tag), and 3. added myself as a contributor. Hope that isn't presumptuous. `[=`

### CODE REVIEW

**Comment by ELLIOTTCABLE** [comment]
Oh, and GitHub is weird about pull-requests. Feel free to manually pull the commits from my fork; and don't forget the release-tag, unless you want me to make some changes and rebase them in.

I'll hit publish on the npm release as soon as you review and fast-forward the upstream! `<3`

**Comment by c-cube** [comment]
Looks nice, just a question: why 0.5.3 and not 0.5.2?

**Comment by ELLIOTTCABLE** [comment]
Because I'm a fool 🤣 

Fixed, rewritten, and pushed!

**Comment by ELLIOTTCABLE** [comment]
You might want to update the homepage in the `package.json` to match — since cedeela.fr doesn't resolve anymore.

Anyway: out on npm! https://www.npmjs.com/package/bs-gen

**Pull request merged**
