### PR TITLE
Revert "Merge pull request #2 from struktured/master"

### PR DESCRIPTION
**Pull request by struktured**
It was noted by @seliopou that fold_map has the same signature as scan. This reverts the fold_map commits (but preserves fold_while).

This reverts commit f920d2aca530dd0c4d0184fc465d3c86ae43e1ca, reversing
changes made to 96578e37c9f55f36d350f66ecea8976aa6b85e5e.

Conflicts:
	gen.ml
	gen_intf.ml

### CODE REVIEW

**Comment by struktured** [comment]
Here's an example of their equivalence. The only discernable difference is scan returns the initial value 
of the successive folds, which is actually better than what fold_map does.

```OCaml
let s = Gen.scan (fun acc x -> acc + x) 0 (Gen.(1--10)) in Gen.to_list s;;
- : int list = [0; 1; 3; 6; 10; 15; 21; 28; 36; 45; 55]                                                                                                                                                                        

let s = Gen.fold_map (fun acc x -> acc + x) 0 (Gen.(1--10)) in Ge.to_list s;;
- : int list = [1; 3; 6; 10; 15; 21; 28; 36; 45; 55]
```

**Comment by c-cube** [comment]
Right, I forgot about this, indeed. I suggest keeping `fold_map`, but as an alias to `scan`, and deprecate the latter in favor of the former (because `fold_map` is indeed more explicit and intuitive a name).

**Comment by struktured** [comment]
Ok, should I mention that fold_map is an alias of "scan" in the ocamldoc?

**Comment by struktured** [comment]
By the way, the term "scan" evidently comes from the haskell terminology:
http://en.wikibooks.org/wiki/Haskell/List_processing#Scans

**Comment by struktured** [comment]
Oh, I suppose you actually want to mark scan as deprecated and refer to fold_map instead. Confirm this and I'll get to it.

Thanks

**Comment by c-cube** [comment]
Yes, I took the name `scan` from Haskell, but `fold_map` is just simpler. Indeed, what I suggest is deprecating `scan` in favor of `fold_map`:

```ocaml
val scan : ....
(** blablabla
     @deprecated use {!fold_map} instead *)
```

**Comment by struktured** [comment]
Don't think these changes are necessary, can reopen if need be.

**Pull request closed without merging**
